### ISSUE TITLE
Swiping is broken for TileLayers

### ISSUE THREAD

**Issue by m-mohr** [Viglino/ol-ext#608]
I implemented swiping some time ago, but recently it broke and I'm getting the following error:

```
Swipe.js:280 Uncaught TypeError: t.target.getClassName is not a function
    at n.postcompose (Swipe.js:280)
    at e (events.js:41)
    at e.dispatchEvent (Target.js:99)
    at e.dispatchComposeEvent_ (Layer.js:93)
    at e.postCompose (Layer.js:126)
    at e.composeFrame (IntermediateCanvas.js:80)
    at e.renderFrame (Map.js:158)
    at e.renderFrame_ (PluggableMap.js:1226)
    at e.<anonymous> (PluggableMap.js:189)
    at e.renderSync (PluggableMap.js:1119)
```

Swipe.js:280 is this line:
`if (e.target.getClassName()!=='ol-layer' && e.target.get('declutter')) {`

For me, `e.target` is a `TileLayer` and I can't find `getClassName` being defined anywhere so I assume that should be `className`?

Changing the line to 
`if (e.target.className !== 'ol-layer' && e.target.get('declutter')) {`
solved it for me, but I'm not sure that's the proper way of fixing it and whether it breaks anything else.

This seems related and could be introduced with #515, I think.

**Comment by mike-000** [comment]
All layers should inherit the `getClassName()` method in OpenLayers 6 but it did not exist in previous version.  If you are using an old version that delay is not needed but to be backward compatible the code should check that `getClassName` exists before calling it.

**Comment by m-mohr** [comment]
Indeed, I'm still on OL 5.3.

**Comment by Viglino** [comment]
Hello,
The last commit should fix it and test if the getClassName method exists.

**Comment by m-mohr** [comment]
Thanks!

**Comment by Viglino** [comment]
Yes it will be integrated in the next release.
